apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elliott-haus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ethanelliott/ethanelliott.ca.git
    targetRevision: HEAD
    path: deployments
    directory:
      recurse: true
      include: '*/application.yaml'
      exclude: 'primary-application.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: elliott-haus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
