replicaCount: 1

image:
  repository: ethanelliottio/camera-frontend
  tag: s-6cead0b
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hostname: 'camera.elliott.haus'

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

# ConfigMap for nginx configuration
configMap:
  enabled: true
  name: camera-frontend-nginx-config
  mountPath: /etc/nginx/conf.d/default.conf
  subPath: nginx.conf
