apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: landing-page
  namespace: elliott-haus
spec:
  project: home
  source:
    repoURL: https://github.com/ethanelliott/ethanelliott.ca.git
    path: deployments/landing-page
    targetRevision: main
    helm:
      releaseName: landing-page
  destination:
    server: https://kubernetes.default.svc
    namespace: elliott-haus
  syncPolicy:
    automated: {}
