replicaCount: 1

image:
  repository: ethanelliottio/landing
  tag: sha-490010b
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hostname: 'elliott.haus'

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

# ConfigMap for nginx configuration
configMap:
  enabled: true
  name: landing-page-nginx-config
  mountPath: /etc/nginx/conf.d/default.conf
  subPath: nginx.conf
