{{- if .Values.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "ai-gateway.fullname" . }}
  labels:
    {{- include "ai-gateway.labels" . | nindent 4 }}
  annotations:
    link.argocd.argoproj.io/external-link: https://{{ .Values.ingress.hostname }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.ingress.hostname }}`)
      middlewares:
        - name: {{ include "ai-gateway.fullname" . }}-cors
      services:
        - name: {{ include "ai-gateway.fullname" . }}
          port: {{ .Values.service.port }}
  tls:
    certResolver: myresolver
{{- end }}
