apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  namespace: elliott-haus
spec:
  project: elliott-haus
  source:
    repoURL: https://github.com/ethanelliott/ethanelliott.ca.git
    path: deployments/kube-state-metrics
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: elliott-haus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
