apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "prometheus.fullname" . }}-data
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size | default "50Gi" }}
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass }}
  {{- end }}
