{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (include "prometheus.fullname" .) }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
{{- end }}
