replicaCount: 1

image:
  repository: ethanelliottio/aritzia-scanner
  tag: s-6cead0b
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  hostname: 'aritzia.elliott.haus'

resources:
  limits:
    cpu: 4
    memory: 2Gi
  requests:
    cpu: 2
    memory: 1Gi

env:
  NODE_ENV: 'production'
  PORT: '3000'
  DB_PATH: '/data/aritzia_stock.sqlite'
  MAX_CONCURRENT_DOWNLOADS: '5'
  DEBUG_LOGGING: 'true'

storage:
  size: 20Gi
  path: /data
