apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wheel
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ethanelliott/ethanelliott.ca.git
    targetRevision: HEAD
    path: deployments/wheel
  destination:
    server: https://kubernetes.default.svc
    namespace: elliott-haus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
