apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recipes-frontend
  namespace: elliott-haus
spec:
  project: elliott-haus
  source:
    repoURL: https://github.com/ethanelliott/ethanelliott.ca.git
    path: deployments/recipes-frontend
    targetRevision: main
    helm:
      releaseName: recipes-frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: elliott-haus
  syncPolicy:
    automated: {}
