apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { include "test-server.fullname" . } }
  labels: { { - include "test-server.labels" . | nindent 4 } }
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels: { { - include "test-server.selectorLabels" . | nindent 6 } }
  template:
    metadata:
      labels: { { - include "test-server.selectorLabels" . | nindent 8 } }
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '{{ .Values.service.port }}'
        prometheus.io/path: '/metrics'
    spec:
      containers:
        - name: { { .Chart.Name } }
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          imagePullPolicy: { { .Values.image.pullPolicy } }
          ports:
            - name: http
              containerPort: { { .Values.service.port } }
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /liveness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readiness
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources: { { - toYaml .Values.resources | nindent 12 } }
          env:
            - name: NODE_ENV
              value: 'production'
            - name: HOST
              value: '0.0.0.0'
            - name: PORT
              value: '{{ .Values.service.port }}'
