{{- if .Values.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "test-server.fullname" . }}
  labels:
    {{- include "test-server.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.ingress.hostname }}`)
      services:
        - name: {{ include "test-server.fullname" . }}
          port: {{ .Values.service.port }}
  tls:
    certResolver: myresolver
{{- end }}
