replicaCount: 1

image:
  repository: ethanelliottio/finances
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  hostname: 'finances-service.elliott.haus'
  cors:
    enabled: true
    allowOrigins:
      - https://finances.elliott.haus

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

env:
  NODE_ENV: 'production'
  HOST: '0.0.0.0'
  PORT: '3000'
  RP_ID: 'finances-service.elliott.haus'
  ORIGIN: 'https://finances.elliott.haus'

storage:
  size: 10Gi
